### ISSUE TITLE
Setting up a pre-production web site in CICD

### ISSUE THREAD

**Issue by alexisbondu** [KhiopsML/khiops-doc#49]
Pour les besoins de modification du site web, il serait interessant de mettre en place un site de pre-prod dans la CICD, dans le but d'interagir sur les nouveaux contenus avant la mise en prod final.

**Comment by folmos-at-orange** [comment]
Done internally: URL https://website-khiops-as-a-service-dev.apps.fr01.paas.tech.orange/
