### ISSUE TITLE
Consider Dropping the Mention of Official Support for MacOS 12

### ISSUE THREAD

**Issue by popescu-v** [KhiopsML/khiops-doc#63]
MacOS 12 support has been dropped from the GitHub runners since December 3rd, 2024: https://github.com/actions/runner-images/issues/10721.

Hence, as this platform could not be automatically tested anymore, we should consider dropping official support for MacOS 12.
Alternatively, MacOS 12 could be in the second tier ("limited support") of a two-tier support policy, with the caveat that *there would be no way to test this platform at all*.

**Comment by folmos-at-orange** [comment]
Resolved in #65
